name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core : ^0.5.0
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3
  email_validator: ^1.0.6
  modal_progress_hud: ^0.1.3
  animated_text_kit: ^2.5.4
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  fonts:
    - family: Faster
      fonts:
        - asset: fonts/FasterOne-Regular.ttf
    - family: Shoju
      fonts:
        - asset: fonts/Shojumaru-Regular.ttf


        
        